# vim: ft=yaml
language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zsh
  - ./tests/install-fish.sh "2.1.1"

install:
  - PATH=$PWD/bin:$PATH

script:
  - ./tests/unit_tests.sh
  - ./tests/integ_tests.sh $PWD
