" vimrc file.
"
" Maintainer:	Filippo Squillace <feel.sqoox@gmail.com>
" Create date:	2014 Nov 09

""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pathogen (https://github.com/tpope/vim-pathogen)
""""""""""""""""""""""""""""""""""""""""""""""""""""
source $PEARL_ROOT/lib/core/category/vim/vim.d/plugins/pathogen/autoload/pathogen.vim
filetype off
call pathogen#infect($PEARL_ROOT.'/mods/vim/{}')
call pathogen#helptags()
filetype plugin indent on
syntax on


""""""""""""""""""
" Module loader
""""""""""""""""""
for config_path in split(globpath($PEARL_ROOT."/lib/core/mods/*/*", '*.vim'), "\n")
    let mod_name = substitute(substitute(config_path, "^.*\/mods\/", "", ""), "\/config\.vim$", "", "")
    if filereadable($PEARL_ROOT."/mods/".mod_name."/.git")
        if filereadable(config_path)
            :exec ":source ".config_path
        endif
    endif
endfor
