#!/bin/bash
# Colorize the hostname
hstcol=$(hostname | sum - | awk '{print 31 + $0 % 6}')

prompt="\[\033[01;31m\][\[\033[1;32m\]\t \[\033[1;33m\]\j \[\e[0;37m\]${SSH_TTY} \[\e[0;32m\[\033[01;31m\]\u@\[\033[01;${hstcol}m\]\h \[\033[01;34m\]\W \[\033[01;35m\]\$\[\033[01;31m\]]> \[\033[00m\]"
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    PS1=$prompt
fi

PROMPT_COMMAND="history -a;" # immediately insert history into history file
case ${TERM} in
  xterm*|rxvt*|Eterm|aterm|kterm|gnome*|vt100)
    PS1=$prompt
    #PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
    ;;

  screen)
    PS1=$prompt
    ;;

  *)
    ;;
esac

unset prompt hstcol

PROMPT_COMMAND='history -a;echo -en "\033[m\033[0;33m"$(( `sed -nu "s/MemFree:[\t ]\+\([0-9]\+\) kB/\1/p" /proc/meminfo`/1024))"\033[35m/"$((`sed -nu "s/MemTotal:[\t ]\+\([0-9]\+\) kB/\1/Ip" /proc/meminfo`/1024 ))MB"\t\033[m\033[36m$(< /proc/loadavg)\033[m\n"'

